# Generated by Django 2.2.16 on 2020-11-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_auto_20201114_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_taken',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='temperature',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='thermo',
            name='date_taken',
            field=models.DateTimeField(null=True),
        ),
    ]
