# Generated by Django 2.2.16 on 2020-11-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_auto_20201114_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
