# Generated by Django 2.2.16 on 2020-11-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_auto_20201114_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_taken',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='thermo',
            name='date_taken',
            field=models.DateTimeField(null=True),
        ),
    ]
