# Generated by Django 2.2.16 on 2020-11-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_auto_20201114_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
