# Generated by Django 2.2.17 on 2020-11-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_temperature_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='thermo',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
