# Generated by Django 2.2.19 on 2021-03-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0011_thermo_matrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermo',
            name='matrix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
